config/routes.rb
Rails.application.routes.draw do
  resources :user_groups 
  
  resources :resources do
    collection do  # id不要
      get 'new_book'
      post 'search'
    end
  end

  resources :users, :param => :login

  resources :tags

  resources :blogs, :param => 'urlkey' do
    match 'admin(/:action)', :controller => 'blog_admin', :via => [:get, :post]

    resources :entries do
      match "preview" => "entries#preview",
            :via => [:get]
      match "set_private" => "entries#set_private",
            :via => [:post]
      match "set_public" => "entries#set_public",
            :via => [:post]

      resources :attaches
    end

    resources :tags
    
    match ":year-:mon" => "blogs#month", 
          :constraints => {:year => /[12][0-9][0-9][0-9]/, :mon => /[01][0-9]/},
          :via => [:get]
  end

  resource :account do
    match "login" => "account#login", :via => [:get]
  end

  root :to => "welcome#index"

  match 'account(/:action(/:id(.:format)))',
        :via => [:get, :post, :patch],
        :controller => "account"

  match '/auth/:provider/callback' => 'auth#callback', :via => [:get, :post]
  
end # draw()

app/models/blog.rb
# -*- coding:utf-8 -*-

# Q's Web Diary
# Copyright (c) 2001,2011 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# ブログ。他のテーブルはここにぶら下がる
class Blog < ApplicationRecord
  # 親
  belongs_to :user_group

  has_many :entries

  def member? user
    return false if !user
    if !user.is_a?(::User)
      user = ::User.find_by_login(user.login)
    end
    return false if !user

    b = Blog.joins("JOIN user_groups ON blogs.user_group_id = user_groups.id LEFT JOIN users_user_groups ON users_user_groups.user_group_id = user_groups.id") \
        .where("users_user_groups.user_id = ?", user.id)
    return b.size > 0
  end


  def members
    # 1段階, 間に挟まっている
    ug_id = user_group_id
    User.joins('JOIN users_user_groups ON users.id = users_user_groups.user_id') \
        .where('user_group_id = ?', ug_id) \
        .select('users.*')    
  end
  
end # class Blog

app/controllers/blogs_controller.rb
# -*- coding:utf-8 -*-

# Q's Web Diary
# Copyright (c) 2001,2011 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# ブログ
# このコントローラは公開ページを扱う. 管理ページは adminコントローラ.
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :month, :edit, :update, :destroy]

  before_action :check_right_to_access_blog,
                :only => [:new, :create, :edit, :update, :destroy]

  layout 'blog', :except => [:index]

  # GET /blogs
  # GET /blogs.json
  # ブログの一覧
  def index
    # 最近の公開エントリが多い順
    # JOIN 内で副問い合わせを行なう. (JOIN してから WHERE でフィルタするとエントリが得られない)
    # => Arel を組み合わせると失敗。混ぜると危険.
    
    join_cond = Entry.where('status <> 0 AND (date BETWEEN ? AND ?)',
                            Date.today - 90, Date.today)
    # left_outer_joins() はActiveRecord 5から.
    @blogs = Blog.joins('LEFT JOIN (' + join_cond.to_sql + ') AS recents ON blogs.id = recents.blog_id') \
                 .group('blogs.id, blogs.name, blogs.lead, blogs.urlkey') \
                 .select('DISTINCT blogs.id, blogs.name, blogs.lead, blogs.urlkey, COUNT(recents) AS cnt') \
                 .order('cnt DESC, blogs.id') \
                 .paginate(:page => params[:page], :per_page => 20)
  end


  # GET /blogs/1
  # GET /blogs/1.json
  # あるブログのトップ。リード文, 最新の記事などを表示.
  def show
    @entries = Entry.paginate(:page => params[:page], :per_page => 5) \
                    .where("blog_id = ? AND status <> 0 AND date <= ?", 
                                 @blog.id, Date.today) \
                    .order("date DESC, id DESC")

    @blog_tags = Tag.public_tags(@blog)
    @blog_members = @blog.members
  end


  # 1ヶ月分 (一般に公開)
  def month
    @mon = Date.new params[:year].to_i, params[:mon].to_i, 1
    @entries = Entry.where("blog_id = ? AND status <> 0 AND (date BETWEEN ? AND ?) AND date <= ?", @blog.id, @mon, (@mon >> 1) - 1, Date.today) \
                    .order("date, id")

    if @entries.empty?
      render :text => "not_found", :status => :not_found
      return
    end
    @blog_tags = Tag.public_tags(@blog)
    @blog_members = @blog.members
  end


  # GET /blogs/new
  def new
    @blog = Blog.new
  end


  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end


  # GET /blogs/1/edit
  def edit
  end


  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


private ##################################################

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    urlkey = params[:blog_urlkey] || params[:urlkey]
    @blog = Blog.find_by_urlkey(urlkey)
    if !@blog
      render :text => "not_found: urlkey = #{urlkey}", :status => :not_found
    end
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def blog_params
    params.fetch(:blog, {})
  end

end # BlogsController

app/views/blogs/_calendar.html.erb
<nav class="calendar">
  <%= tag "a", {:href => "/blogs/#{@blog.urlkey}"}, true %>最新</a>

<% e = Entry.where("blog_id = ? AND status <> 0", @blog.id) \
            .order("date").first
   ( (e ? e.date.year : Date.today.year).. Date.today.year).each do |y| %>
  <div class="year">
<%= y %>年 | 
<%   (1..12).each do |m| 
       if Entry.where("blog_id = ? AND status <> 0 AND (date BETWEEN ? AND ?)",
                      @blog.id, Date.new(y, m, 1), 
                      (Date.new(y, m, 1) >> 1) - 1) \
               .first %>
<%= tag "a", {:href => sprintf("/blogs/%s/%04d-%02d", @blog.urlkey, y, m)}, true %>
  <%= sprintf("%02d", m) %>
</a>
<%     else %>
  <%= sprintf("%02d", m) %>
<%     end 
     end %>
  </div>
<% end %>
</nav>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% @page_title = "ブログの一覧" %>



<% @blogs.each do |blog|
     # 全件数
     entry_cnt = Entry.where('blog_id = ? AND status <> 0', blog.id).select('COUNT(*) as cnt').order('').first %>
<p><%= link_to "#{blog.name.blank? ? "no named blog" : blog.name}(#{entry_cnt.cnt})", :controller => "blogs", :action => "show", :urlkey => blog.urlkey %>
  <%= Sanitize.clean(blog.lead, Sanitize::Config::RESTRICTED)[0..200].html_safe %>
<% end %>

app/views/blogs/month.html.erb
<% @page_title = "#{@mon.year}年#{@mon.mon}月" %>
<% @crumbs = [
   {:title => @blog.name, :controller => 'blogs', :action => 'show', :urlkey => @blog.urlkey}
   ] %>


<%= render :partial => "calendar" %>

<hr class="sep" />




<% if @entries.empty? %>

<p>公開エントリは一つもありません。

<% else %>

<%   @entries.each do |entry| %>
<%= render :partial => "entries/show", :locals => {:entry => entry} %>
<%   end %>

<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<% @page_title = "最新" %>



<%= render :partial => "calendar" %>


<hr class="sep" />

<% if @entries.empty? %>

<p>公開エントリは一つもありません。

<% else %>

<%= will_paginate @entries, blog_paginate_options() %>

<%   @entries.each do |entry| %>
  <%= render :partial => "entries/show", :locals => {:entry => entry} %>
<%   end %>

<%= will_paginate @entries, blog_paginate_options() %>

<% end %>