config/routes.rb
Rails.application.routes.draw do
  resources :user_groups 
  
  resources :resources do
    collection do  # id不要
      get 'new_book'
      post 'search'
    end
  end

  resources :users, :param => :login

  resources :tags

  resources :blogs, :param => 'urlkey' do
    match 'admin(/:action)', :controller => 'blog_admin', :via => [:get, :post]

    resources :entries do
      match "preview" => "entries#preview",
            :via => [:get]
      match "set_private" => "entries#set_private",
            :via => [:post]
      match "set_public" => "entries#set_public",
            :via => [:post]

      resources :attaches
    end

    resources :tags
    
    match ":year-:mon" => "blogs#month", 
          :constraints => {:year => /[12][0-9][0-9][0-9]/, :mon => /[01][0-9]/},
          :via => [:get]
  end

  resource :account do
    match "login" => "account#login", :via => [:get]
  end

  root :to => "welcome#index"

  match 'account(/:action(/:id(.:format)))',
        :via => [:get, :post, :patch],
        :controller => "account"

  match '/auth/:provider/callback' => 'auth#callback', :via => [:get, :post]
  
end # draw()

app/models/accounts/user_group.rb
# -*- coding:utf-8 -*-

module Accounts
  # スペース
  class UserGroup < Accounts::Base
    # 多対多
    has_many :user_groups_users
    has_many :users, :through => :user_groups_users
  end
end

app/models/user_group.rb
# -*- coding:utf-8 -*-


# ユーザグループ
class UserGroup < ActiveRecord::Base
  # 多対多
  has_many :users_user_groups
  has_many :users, :through => :users_user_groups

  # 所有
  has_many :blogs


  def member? user
    return false if !user
    
    if user.class.to_s == "Accounts::User"
      user = ::User.find_by_login(user.login)
    end
    if user.class.to_s != "User"
      raise TypeError, "user must be a User/Accounts::User, but #{user.class}" 
    end

    g = UsersUserGroup.where("user_id = ? AND user_group_id = ?",
                             user.id, self.id).first
    return (g ? true : false)
  end

end # class UserGroup

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
    raise # TODO: impl.
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    raise # TODO: impl.
    
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    raise # TODO: impl.
    
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    raise # TODO: impl.
    
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.fetch(:user_group, {})
    end
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing User Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Groups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_groups.each do |user_group| %>
      <tr>
        <td><%= link_to 'Show', user_group %></td>
        <td><%= link_to 'Edit', edit_user_group_path(user_group) %></td>
        <td><%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>