config/routes.rb
Rails.application.routes.draw do
  resources :user_groups 
  
  resources :resources do
    collection do  # id不要
      get 'new_book'
      post 'search'
    end
  end

  resources :users, :param => :login

  resources :tags

  resources :blogs, :param => 'urlkey' do
    match 'admin(/:action)', :controller => 'blog_admin', :via => [:get, :post]

    resources :entries do
      match "preview" => "entries#preview",
            :via => [:get]
      match "set_private" => "entries#set_private",
            :via => [:post]
      match "set_public" => "entries#set_public",
            :via => [:post]

      resources :attaches
    end

    resources :tags
    
    match ":year-:mon" => "blogs#month", 
          :constraints => {:year => /[12][0-9][0-9][0-9]/, :mon => /[01][0-9]/},
          :via => [:get]
  end

  resource :account do
    match "login" => "account#login", :via => [:get]
  end

  root :to => "welcome#index"

  match 'account(/:action(/:id(.:format)))',
        :via => [:get, :post, :patch],
        :controller => "account"

  match '/auth/:provider/callback' => 'auth#callback', :via => [:get, :post]
  
end # draw()

app/models/tag.rb
# -*- coding:utf-8 -*-

# Q's Web Diary
# Copyright (c) 2001,2011 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# タグ
# タグそのものは、特定の blog ではなく, グローバルに持つ.
class Tag < ApplicationRecord
  # 多対多
  has_many :entries_tags
  has_many :entries, :through => :entries_tags

  belongs_to :created_by, :foreign_key => "create_user_id", 
                                                    :class_name => "User"

  validates_presence_of :name

  class << self
    def public_tags(blog)
      tags = Tag.joins('JOIN entries_tags ON tags.id = entries_tags.tag_id JOIN entries ON entries_tags.entry_id = entries.id') \
                .where('entries.status <> 0 AND entries.date <= ?', Date.today) \
                .group('tags.id, tags.name') \
                .select('tags.id, tags.name, COUNT(entries_tags) AS cnt')
      if blog
        return tags.where("blog_id = ?", blog.id)
      else
        return tags
      end
    end
  end # class << self
end # class Tag

app/controllers/tags_controller.rb
# -*- coding:utf-8 -*-

# Q's Web Diary
# Copyright (c) 2001,2011 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# エントリに付けるタグ
# ブログのなかの tags URL と /tagsがある.
class TagsController < ApplicationController
  before_action :set_blog

  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  #layout 'blog' #, :only => [:show, :preview]

  
  # GET /tags
  # GET /tags.json
  # タグの一覧 (公開ページのみ)
  def index
    @ets = Tag.public_tags(@blog)
    if @blog
      render :layout => 'blog'
    end
  end


  # GET /tags/1
  # GET /tags/1.json
  # あるタグを含むエントリの一覧 (公開ページのみ)
  def show
    ents = Entry.select("DISTINCT entries.*") \
                 .joins("LEFT JOIN entries_tags ON entries.id = entries_tags.entry_id") \
                 .order('entries.date DESC') \
                 .paginate(:page => params[:page], :per_page => 20)
    if @blog
      @entries = ents.where("blog_id = ? AND entries.status <> 0 AND entries.date <= ? AND entries_tags.tag_id = ?", 
                            @blog.id, Date.today, @tag.id)
      @blog_tags = Tag.public_tags(@blog)
      @blog_members = @blog.members
      
      render :layout => 'blog'
    else
      @entries = ents.where("entries.status <> 0 AND entries.date <= ? AND entries_tags.tag_id = ?", 
                            Date.today, @tag.id)
    end
  end


private ###################################################

  def set_blog
    @blog = params[:blog_urlkey].blank? ? nil :
                                  (Blog.find_by_urlkey params[:blog_urlkey])
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def tag_params
    params.fetch(:tag, {})
  end

end # TagsController

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<% @page_title = "タグの一覧" %>



<%   @ets.each do |tag| %>
<p><%= link_to "#{tag.name}(#{tag.cnt})", :action => 'show', :id => tag, :blog_id => @blog %>
<% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<% @page_title = "タグ: " + @tag.name %>
<% if @blog %>
<% @crumbs = [
   {:title => @blog.name, :controller => 'blogs', :action => 'show', :urlkey => @blog.urlkey}
   ] %>
<% end %>

<% if @blog %>
<p><%= link_to "すべてのブログ", "/tags/#{@tag.id}" %>
<% end %>


<%= will_paginate @entries, blog_paginate_options() %>

<%= render :partial => 'entries/entry_leads',
           :locals => {:entries => @entries} %>

<%= will_paginate @entries, blog_paginate_options() %>